### ISSUE TITLE
[BUG] - sqlalchemy 2.0.0 includes breaking changes

### ISSUE THREAD

**Issue by iameskild** [nebari-dev/nebari-jupyterhub-theme#14]
### Describe the bug

The `2023.1.1` release of the nebari-jupyterhub-theme causes problems for jupyterhub trying to spawn.

### Expected behavior

Jupyterhub should spin up without any issues. 

### How to Reproduce the problem?

Deploy nebari with the image tag for jupyterhub set to `2023.1.1`.

### Command output

```bash session
Loading /usr/local/etc/jupyterhub/secret/values.yaml
No config at /usr/local/etc/jupyterhub/existing-secret/values.yaml
Loading extra config: 01-theme.py
Loading extra config: 02-spawner.py
Loading extra config: 03-profiles.py
[I 2023-01-31 23:39:11.990 JupyterHub app:2479] Running JupyterHub version 1.5.0
[I 2023-01-31 23:39:11.990 JupyterHub app:2509] Using Authenticator: oauthenticator.generic.GenericOAuthenticator-14.1.0
[I 2023-01-31 23:39:11.990 JupyterHub app:2509] Using Spawner: cdsdashboards.hubextension.spawners.variablekube.VariableKubeSpawner-0.6.3
[I 2023-01-31 23:39:11.990 JupyterHub app:2509] Using Proxy: jupyterhub.proxy.ConfigurableHTTPProxy-1.5.0
[E 2023-01-31 23:39:12.002 JupyterHub app:2989]
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.9/site-packages/jupyterhub/app.py", line 2986, in launch_instance_async
        await self.initialize(argv)
      File "/opt/conda/lib/python3.9/site-packages/jupyterhub/app.py", line 2521, in initialize
        self.init_db()
      File "/opt/conda/lib/python3.9/site-packages/jupyterhub/app.py", line 1723, in init_db
        dbutil.upgrade_if_needed(self.db_url, log=self.log)
      File "/opt/conda/lib/python3.9/site-packages/jupyterhub/dbutil.py", line 112, in upgrade_if_needed
        orm.check_db_revision(engine)
      File "/opt/conda/lib/python3.9/site-packages/jupyterhub/orm.py", line 811, in check_db_revision
        alembic_revision = engine.execute(
    AttributeError: 'Engine' object has no attribute 'execute'
    
Stream closed EOF for dev/hub-8c4d6f865-8cxqn (hub)
```

**Comment by iameskild** [comment]
@trallard I ran into this issue when I was testing the most recent changes to the `nebari-jupyterhub-theme==2023.1.1`. Unfortunately I don't have time to resolve this issue today ahead of the release so I have pinned the theme version to the previously working version for now: https://github.com/nebari-dev/nebari-docker-images/pull/48

**Comment by iameskild** [comment]
This appears to be due to a recent sqlalchemy release:  https://github.com/sqlalchemy/sqlalchemy/releases/tag/rel_2_0_0

**Comment by iameskild** [comment]
Closed by: https://github.com/nebari-dev/nebari-docker-images/pull/49
